sudo: required
services:
  - docker

before_install:
  - docker build -t issabayevmk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true issabayevmk/react-test npm test -- --coverage

after_success:
  - docker build -t issabayevmk/multi-client ./client
  - docker build -t issabayevmk/multi-nginx ./nginx
  - docker build -t issabayevmk/multi-server ./server
  - docker build -t issabayevmk/multi-worker ./worker