sudo: required
services:
  - docker

before_install:
  - docker build -t issabayevmk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true issabayevmk/react-test npm test -- --coverage

after_success:
  - docker build -t issabayevmk/multi-client ./client
  - docker build -t issabayevmk/multi-nginx ./nginx
  - docker build -t issabayevmk/multi-server ./server
  - docker build -t issabayevmk/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push issabayevmk/multi-client
  - docker push issabayevmk/multi-nginx
  - docker push issabayevmk/multi-server
  - docker push issabayevmk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket-name: 'elasticbeanstalk-us-east-1-424397075683'
  bucket-path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY